In [1]:
import numpy as np
# This is assignment for numPy

In [5]:
# 1. Write a NumPy program to test whether none of the elements of a given array is zero.
noneZero = np.array([1,2,3,4,5,5,6,21,21,2,2,2,1])
withZero = np.array([1,2,3,4,5,0,0,2,12])
print(np.all(noneZero != 0))
print(np.all(withZero != 0))

True
False


In [6]:
# 2. Write a NumPy program to test whether any of the elements of a given array is non-zero.
allZeros = np.array([0,0,0,0,0,0,0,0,0,0])
notAllZeros = np.array([1,2,34,5,0,12,0,12])
print("the array with name {allZeros} has result",np.all(allZeros == 0))
print("the array with name {notAllZeros} has result",np.all(notAllZeros == 0))

the array with name {allZeros} has result True
the array with name {notAllZeros} has result False


In [7]:
# 3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given
first = np.array([1,2,3,4,5,6,2,1])
second = np.array([1,3,3,4,1,2,3,4])
print(first == second)
# I Do Not Understadn The Second Task????

[ True False  True  True False False False False]


In [12]:
# 4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
zeros = np.full(10,0)
#another method
# zeros = np.zeros(10)
ones = np.full(10,1)
fives = np.full(10,5)
# sumAll = zeros.sum() + ones.sum() + fives.sum()
sumAll = np.concatenate((zeros,ones,fives))
print(sumAll)
sumAll.sum()

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 5 5 5 5 5 5 5 5 5 5]


60

In [13]:
#  5. Write a NumPy program to create an array of the integers from 30 to70.
array = np.arange(30,71)
array

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [15]:
# 6. Write a NumPy program to create a 3x3 identity matrix
oneDim = np.array([1,2,3,4])
threeDim = oneDim.reshape(2,2,1)
print("first Array Is \n",threeDim)
# another way
hello = np.eye(3)
print("Second Array Is: \n",hello)

first Array Is 
 [[[1]
  [2]]

 [[3]
  [4]]]
Second Array Is: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
# 7. Write a NumPy program to generate a random number between 0 and 1
# random number between 0 and 1
randomNumber = np.random.rand()
print(randomNumber)
# rnadom number between specific range
start = 2
end = 10
random2 = np.random.uniform(start,end)
print(random2)

0.9297747285292445
9.187299787084877


In [ ]:
# 8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution
# standard normal distribution ????????????
randomArray = np.random.randn(15)
print(randomArray)
# make array with random values between specifc range
start = 0
end = 10
hello = np.random.uniform(start,end,15)
print(hello)

In [23]:
# 9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.
allValues = np.arange(15,56)
print(allValues[1:])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [24]:
# 10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10
randomArray = np.random.uniform(0,10,5)
print(randomArray)

[6.92785131 0.36344942 9.35527807 7.12701111 1.34950666]


In [25]:
# 11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
matrix = np.full((10,10),0)
matrix[0,:10] = matrix[:,0] = matrix[:,9] = matrix[9,:] = 1
print(matrix)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [27]:
 # 12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
matrix = np.diag([1, 2, 3, 4, 5])
print("main matrix is ",matrix)
seocnd = np.eye(5)*[1,2,3,4,5]
print("second array is \n",seocnd)
third = np.diagflat([1, 2, 3, 4, 5])
print("third array is\n", third)
fourth = np.full((5,5),0)
np.fill_diagonal(fourth, [1, 2, 3, 4, 5])
print("fourth matrix is \n",fourth)
# if you want to replace zeros with specifc number
# matrix = np.where(matrix == 0,9,matrix)

main matrix is  [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
second array is 
 [[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]
third array is
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
fourth matrix is 
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [28]:
# 13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
matrix = np.array([[1, 0, 1, 0],
                   [0, 1, 0, 1],
                   [1, 0, 1, 0],
                   [0, 1, 0, 1]])

np.fill_diagonal(matrix, 0)

print(matrix)

[[0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]]


In [ ]:
#14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.
# I Do Not Understand The Question

In [29]:
# 15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select
randomArray = np.random.rand(40)
print("all random array is",randomArray)
start =  0
end = 20
print("selected range is \n",randomArray[start:end])

all random array is [0.54487364 0.74789582 0.17036417 0.92146816 0.23469119 0.17081777
 0.48195269 0.67027783 0.45844107 0.31673155 0.07300852 0.972862
 0.13402112 0.95189861 0.17211297 0.79271608 0.78689725 0.04839846
 0.57780373 0.67227372 0.7515222  0.91097458 0.88519478 0.41900545
 0.91195782 0.48432744 0.15334691 0.5922953  0.47618406 0.23992608
 0.12217944 0.08473795 0.337215   0.01006855 0.0418879  0.28696808
 0.8592532  0.71708891 0.09947939 0.66286682]
selected range is 
 [0.54487364 0.74789582 0.17036417 0.92146816 0.23469119 0.17081777
 0.48195269 0.67027783 0.45844107 0.31673155 0.07300852 0.972862
 0.13402112 0.95189861 0.17211297 0.79271608 0.78689725 0.04839846
 0.57780373 0.67227372]


In [30]:
# 16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.
mainArray = np.array([1,2,3,4,5,6,22,2,2])
value = 2
otherValues = mainArray[(mainArray < value) | (mainArray > value)]
print(otherValues)

[ 1  3  4  5  6 22]
